### ISSUE TITLE
[ui5-tooling-transpile] Configure interface generation jsdoc output level

### ISSUE THREAD

**Issue by ybbus** [ui5-community/ui5-ecosystem-showcase#1109]
We generate the interfaces of our custom controls using:
npx @ui5/ts-interface-generator
This is done in the precommit-hook and it generates interfaces with comments.

But in the pre-push hook we run the qunit and OPA tests and this starts up the UI5 dev server (ui5 serve) which also generates the interfaces again, but without comments.

This leaves us with a dirty local working directory on each push, what is quite annoying.

One solution would be to disable interface generation:
```yaml
- name: ui5-tooling-transpile-middleware
          afterMiddleware: compression
          configuration:
              generateTsInterfaces: false
```

But a better solution would be, that the transpile middleware offers a configuration for the jsdoc generation.

This could lool something lilke:
```yaml
- name: ui5-tooling-transpile-middleware
  afterMiddleware: compression
  configuration:
    generateTsInterfacesJSDoc: none | minimal | verbose
```
