### ISSUE TITLE
[ui5-tooling-modules] failed to load JavaScript resource for jspdf

### ISSUE THREAD

**Issue by mmotkim** [ui5-community/ui5-ecosystem-showcase#1128]
**Describe the bug**
I'm working on an adaptation project, I've been following the documentation on [www.npmjs.com/package/ui5-tooling-modules](www.npmjs.com/package/ui5-tooling-modules) and got the library excelJS to work. I cleared the excel-related code and proceeded to use [jspdf](www.npmjs.com/package/jspdf) when I could not get it to work.
I've tried tweaking witth `skipTransform` `skipCache: true` `inject:` and still to no avail, 
interestingly I also can't get `debug: true` to work. It creates the same log whether I'm using `npm run start` or `npm run build`.
I've been scratching my head at this thing for 3 days now.
**To Reproduce**
1. Create Adaptation Project from generator templates on vscode that connect to a sap system backend (uses fiori-tools-proxy)
2. Configure according to [www.npmjs.com/package/ui5-tooling-modules](www.npmjs.com/package/ui5-tooling-modules)
3. `npm i jspdf`
4. Import jsPDF and Application Preview

**Screenshots**
![Image](https://github.com/user-attachments/assets/2b583c6f-44ac-458f-a7e1-54224973225e)
![Image](https://github.com/user-attachments/assets/9e885c27-b3eb-4958-b8ff-d47784d90fe6)

**Code**
Here's my ui5.yaml:
```
# yaml-language-server: $schema=https://sap.github.io/ui5-tooling/schema/ui5.yaml.json

specVersion: "3.0"
metadata:
  name: atpreportvariant
type: application
resources:
  configuration:
    propertiesFileSourceEncoding: UTF-8
customConfiguration:
  adp:
    support:
      id: "@sap/generator-adaptation-project"
      version: 1.1.63
      toolsId: 09edfc9e-5876-4488-a154-8d943eb1994e
  ui5-tooling-modules: &cfgModules
    skipCache: true
    skipTransform:
      - "@jspdf/dist/jspdf.es.*"
      - "@jspdf/dist/jspdf.node.*"
    debug: "true"
builder:
  customTasks:
    - name: ui5-tooling-modules-task
      afterTask: replaceVersion
      configuration:
        <<: *cfgModules
        debug: true
server:
  customMiddleware:
    - name: ui5-tooling-modules-middleware
      afterMiddleware: compression
      configuration:
        debug: true
        <<: *cfgModules
        inject:
          jsPDF: jspdf
    - name: fiori-tools-appreload
      afterMiddleware: ui5-tooling-modules-middleware
      configuration:
        port: 35729
        path: webapp
        delay: 300
    - name: fiori-tools-preview
      afterMiddleware: fiori-tools-appreload
      configuration:
        adp:
          target:
            client: "302"
            url: https://s35.gb.ucc.cit.tum.de
          ignoreCertErrors: false
    - name: fiori-tools-proxy
      afterMiddleware: fiori-tools-preview
      configuration:
        ignoreCertError: false # If set to true, certificate errors will be ignored. E.g. self-signed certificates will be accepted
        backend:
          - client: "302"
            url: https://s35.gb.ucc.cit.tum.de
            path: /sap
        ui5:
          path:
            - /resources
            - /test-resources
          url: https://ui5.sap.com
          version: 1.108.33
```

Here's my package.json:
```
{
    "name": "atpreportvariant",
    "version": "0.1.0",
    "private": true,
    "description": "ATP Report",
    "keywords": [
        "ui5",
        "sapui5",
        "adaptation-project"
    ],
    "devDependencies": {
        "@sap/ux-ui5-tooling": "1",
        "@ui5/cli": "^3.9.2",
        "@ui5/task-adaptation": "^1.3.0",
        "ui5-tooling-modules": "^3.18.7"
    },
    "scripts": {
        "build": "ui5 build --exclude-task generateFlexChangesBundle generateComponentPreload minify --clean-dest",
        "start": "fiori run --open /test/flp.html#app-preview",
        "start-editor": "fiori run --open /test/adaptation-editor.html"
    },
    "dependencies": {
        "exceljs": "^4.4.0",
        "jspdf": "^2.5.2"
    }
}
```

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Node.js: Been switching between v22, v20 and v18

P/S: I'm happy to share my entire source code for your further inspection.

**Comment by petermuessig** [comment]
Hi @mmotkim,

as you suggest, maybe you could provide me your source code (if you are SAP internal, just write to me internally to share the source code). This would make the analysis easier. I'm wondering a bit why you exclude jsPDF from transformation. The debug flag should be `debug: true` - no string. Do you somewhere have a `resourceroots` or `sap.ui.loader.config` configuration which maps jsPDF to another place? 

THX and BR,
Peter

**Comment by mmotkim** [comment]
@petermuessig Yes it does, [http://localhost:8080/resources/pdf-lib.js](http://localhost:8080/resources/pdf-lib.js) returns the code starting with ``` 
**sap.ui.define**(['exports', 'customer/atpreportvariant/resources/_commonjsHelpers'], (function (exports, _commonjsHelpers) { 'use strict';

    var tslib = {exports: {}};

    (function (module) {
      var __extends;
```

**Comment by mmotkim** [comment]
I added your `sap.ui.loader.config` and it still produced the same error, also when I tried to add the jspdf dependency reroute like this:
```
sap.ui.loader.config({
  paths: {
    "pdf-lib": "/resources/pdf-lib",
    "_commonjsHelpers.js": "/resources/_commonjsHelpers.js",
  },
});
```
![Image](https://github.com/user-attachments/assets/994db64d-ec7a-4a3b-8b59-881e13bc6eb5)

**Comment by petermuessig** [comment]
For the `_commonjsHelper` you need to avoid the file extension `.js` - but it underlines my assumption that it is related to the application variant running the code in context of the application and thus tries to load the `app/resources/*` relative to the application path. Maybe the proxy can be configured in a way that it re-routes to the server roots` `/resource*`?

**Comment by mmotkim** [comment]
But when I used ExcelJS for the application variant at first it worked flawlessly, Only when adding pdf-js/removing ExcelJS and adding pdf-js that it cried about not being able to load the .js

**Comment by petermuessig** [comment]
What you can do is the following - add a `backend` mapping for the `/custom/atpreportvariant/resources` to the `fiori-tools-proxy` configuration and map it to `http://localhost:8080`:

```yaml
    - name: fiori-tools-proxy
      afterMiddleware: fiori-tools-appreload
      configuration:
        debug: true
        ignoreCertError: false # If set to true, certificate errors will be ignored. E.g. self-signed certificates will be accepted
        backend:
          - client: "302"
            url: https://s35.gb.ucc.cit.tum.de
            path: /sap
          - path: /customer/atpreportvariant/resources
            pathReplace: /resources
            url: http://localhost:8080
        ui5:
          path:
            - /resources
            - /test-resources
          url: https://ui5.sap.com
          version: 1.108.33

```

**Comment by mmotkim** [comment]
Alright, I removed `sap.ui.loader.config` then ran the Preview, retrying with keeping your proxy config and not keeping.
There were 2 failed GET reqs with the same URL and headers in both tries: 
`http://localhost:8080/sap/bc/ui5_ui5/sap/zatpr/~3652DD8F6F55485147ACA7924D0C9999~5/resources/_commonjsHelpers.js`

Headers
```
GET /sap/bc/ui5_ui5/sap/zatpr/~3652DD8F6F55485147ACA7924D0C9999~5/resources/_commonjsHelpers.js HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate, br, zstd
Accept-Language: en-US,en;q=0.9,vi;q=0.8
Connection: keep-alive
Cookie: sap-usercontext=sap-language=EN&sap-client=302; SAP_SESSIONID_S35_302=aNKFm2sFP6UW1JUxJqk4bHKynoWyDxHvmE9ldA41RTs%3d
Host: localhost:8080
Referer: http://localhost:8080/test/flp.html
Sec-Fetch-Dest: script
Sec-Fetch-Mode: no-cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0
sec-ch-ua: "Microsoft Edge";v="131", "Chromium";v="131", "Not_A Brand";v="24"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
```

**Comment by petermuessig** [comment]
@mmotkim 

Please try to following configuration in the proxy:

```yaml
          - path: /sap/bc/ui5_ui5/sap/zatpr/~3652DD8F6F55485147ACA7924D0C9999~5/resources
            pathReplace: /resources
            url: http://localhost:8080
```

What I don't like is the static definition of the cachebuster token in the URL - but it should be at least for the whole application - so it may work then for all the requests. 

@tobiasqueck @Klaus-Keller - is it possible to use a regex in the Fiori tools proxy? I tried it but I run into an endless loop. Maybe this would be an interesting feature to proxy such kind of requests and to be able to ignore the cachebuster token segment. THX

**Comment by mmotkim** [comment]
There were still 2 of those same failed requests URLs.

I add the config to fiori-tools-proxy like this:
```
customMiddleware:
    - name: ui5-tooling-modules-middleware
      afterMiddleware: compression
    - name: fiori-tools-appreload
      afterMiddleware: ui5-tooling-modules-middleware
      configuration:
        port: 35729
        path: webapp
        delay: 300
    - name: fiori-tools-preview
      afterMiddleware: fiori-tools-appreload
      configuration:
        adp:
          target:
            client: "302"
            url: https://s35.gb.ucc.cit.tum.de
          ignoreCertErrors: false
    - name: fiori-tools-proxy
      afterMiddleware: fiori-tools-preview
      configuration:
        ignoreCertError: false
        backend:
          - client: "302"
            url: https://s35.gb.ucc.cit.tum.de
            path: /sap
          # - path: /customer/atpreportvariant/resources
          #   pathReplace: /resources
          #   url: http://localhost:8080
          - path: /sap/bc/ui5_ui5/sap/zatpr/~3652DD8F6F55485147ACA7924D0C9999~5/resources
            pathReplace: /resources
            url: http://localhost:8080
        ui5:
          path:
            - /resources
            - /test-resources
          url: https://ui5.sap.com
          version: 1.108.33
```

Header:
```
GET /sap/bc/ui5_ui5/sap/zatpr/~3652DD8F6F55485147ACA7924D0C9999~5/resources/_commonjsHelpers.js HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate, br, zstd
Accept-Language: en-US,en;q=0.9,vi;q=0.8
Connection: keep-alive
Cookie: SAP_SESSIONID_S72_303=PZR_kj4zZEv-vt4E_njy4-SfuuN9ahHvlNg1w4k9tpc%3d; SAP_SESSIONID_E04_912=D2HplAfkj6vGszSSZk_Xj9-Xc9uPfRHvqgbDLncbQbI%3d; sap-usercontext=sap-language=EN&sap-client=302; SAP_SESSIONID_S35_302=Hsh3TpoZw1KR1agDsma1DnMkl1KyFhHvl2pldA41RTs%3d
Host: localhost:8080
Referer: http://localhost:8080/test/flp.html
Sec-Fetch-Dest: script
Sec-Fetch-Mode: no-cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0
sec-ch-ua: "Microsoft Edge";v="131", "Chromium";v="131", "Not_A Brand";v="24"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
```

I used Text compare to make sure the static definitions in the urls were identical, is there something preventing proxy configuration from catching the path?

**Comment by tobiasqueck** [comment]
@petermuessig @mmotkim I don't think your setup is a good idea. I am also not sure how this is supposed to work after deployment. 
Let me explain what I understood and what concerns me:
* you have an on-prem system (or at least not an S/4HANA Cloud Public Edition) - that's important because it means your adaptation will be deployed to LREP and not as a BSP like an app
* in your local setup you use a middleware to pretend that `jspdf` will be part of the deployed bundle
   * Does this actually work when being deployed to LREP? It might be but I have never seen it, so I would test this first before further looking into a local setup
* for a reason that I could not understand, your app "thinks" that it can find the `jspdf` module at `/sap/bc/ui5_ui5/sap/zatpr/~3652DD8F6F55485147ACA7924D0C9999~5/resources`
   * My guess is that you already deployed the `jspdf` module as a reuse library in your ABAP backend
   * Since your ADP knows about, I assume it is already declared in the `manifest.json` of the original app - or you added a change to your ADP that adds the reuse lib
   * Is my understanding correct or did I misunderstand something?

If my assumptions are correct then removing the `ui5-tooling-modules-middleware` as well as the additional configuration you added to the `fiori-tools-proxy` and the `sap.ui.loader.config` should solve the problem because the `fiori-tools-preview` would resolve the url of your reuse lib during startup.

**Comment by mmotkim** [comment]
Let me further elaborate on the reproduction steps:

1. Connecting an on-premise system, I used `@sap/generator-fiori` on VSCode using the analytical list page template. It was then deployed as an BSP only using [nwabap-ui5uploader](https://www.npmjs.com/package/nwabap-ui5uploader)
2. I then used `@sap/generator-adaptation-project` to create an adaptation application from that BSP on the system. The generator already set up the proxy for me according to the system info provided.
3. In order to use `ui5-tooling-modules` after adding `name: ui5-tooling-modules-middleware` I had to line up `fiori-tools-proxy` to run after `ui5-tooling-modules-middleware`. It was this afterMiddleware property that I had to change so that the preview doesn't show up as blank.
```javascript
    - name: fiori-tools-appreload
      afterMiddleware: ui5-tooling-modules-middleware
``` 
The middleware should run in order of `ui5-tooling-modules-middleware` -> `fiori-tools-appreload` -> `fiori-tools-preview`  -> `fiori-tools-proxy` If I understand correctly
4. I used `npm i ExcelJS` and got it to work just fine, but `npm i jspdf` caused this whole issue. I didn't deploy any reuse libraries to the backend.

Hope it can help, @tobiasqueck

**Comment by tobiasqueck** [comment]
@mmotkim a few more question to ensure I got the full picture:

* Is`/sap/bc/ui5_ui5/sap/zatpr` the path of your ALP i.e. the original app?
* You intend to deploy `jspdf` as part of your ADP?
* Your original ALP doesn't refer to `jspdf` at all?

> I used npm i ExcelJS and got it to work just fine, but npm i jspdf caused this whole issue.

That one confuses me. The only reason that I could guess would be that your original app already knows one of the two. Is that the case?

**Comment by petermuessig** [comment]
@tobiasqueck - the application variant comes with a custom code `ExportToExcel.js` which includes thirdparty. Therefore @mmotkim uses the ui5-tooling-modules to access it. As the UI5 resources are loaded relative to the application variant in the ABAP system, we need to redirect it for the local development to the localhost UI5 dev server so that the `ui5-tooling-modules` middleware can process it.

Now, for the deployment, there should be no issue anymore - as the build is prefixing the imports of the thirdparty with the namespace of the application variant - see here the build output of the `ExportToExcel.js`: 

![Image](https://github.com/user-attachments/assets/105d901b-d663-45c6-9999-14e9e9fbca0b)

With that the thirdparty is addressed relative to the application variant and I don't see a problem here.

The main issue was about pointing the thirdparty requests during development to the `ui5-tooling-modules` middleware since the proxy catched the requests and proxied them to the ABAP server instead.

**Comment by tobiasqueck** [comment]
> The main issue was about pointing the thirdparty requests during development to the ui5-tooling-modules middleware since the proxy catched the requests and proxied them to the ABAP server instead.

That is what confuses me because the preview middleware generates an html (you can check the source in the browser when testing) that tells UI5 to find all the original app files and the adaptation files at `/`. You should not need an additional redirect in your `ui5.yaml`. That's why I still believe the deployed ADP won't work because something is missing that I haven't understood yet.

**Comment by petermuessig** [comment]
> > The main issue was about pointing the thirdparty requests during development to the ui5-tooling-modules middleware since the proxy catched the requests and proxied them to the ABAP server instead.
> 
> That is what confuses me because the preview middleware generates an html (you can check the source in the browser when testing) that tells UI5 to find all the original app files and the adaptation files at `/`. You should not need an additional redirect in your `ui5.yaml`. That's why I still believe the deployed ADP won't work because something is missing that I haven't understood yet.

But the thirdparty is not rewritten so far during local development. The rewrite (prefix with the application namespace) only takes place during the build. I already thought about this feature but it would again require a bigger rework. Maybe there's some time during the next x-mas vacation for that... ;-)

**Comment by tobiasqueck** [comment]
@petermuessig would `addToNamespace: true` in the `ui5-tooling-modules-middleware` config maybe solve the problem?

**Comment by tobiasqueck** [comment]
> This is exactly the missing feature which would solve it in general. Right now, all thirdparty requests will go through /resources/* and not through the application namespace...

Sorry, I wrote my response before I read your last message. Now I am getting the problem!

**Comment by petermuessig** [comment]
Related issue: https://github.com/ui5-community/ui5-ecosystem-showcase/issues/1049

**Comment by tobiasqueck** [comment]
It's a misuse of a feature but could you try the following in your preview-middleware config:

```
- name: fiori-tools-preview
      afterMiddleware: fiori-tools-appreload
      configuration:
        flp:
          apps:
          - target: /resources
             componentId: customer.atpreportvariant.resources
        adp:
          target:
            client: "302"
            url: https://s35.gb.ucc.cit.tum.de
          ignoreCertErrors: false
```
That's a wild guess that may work ...

**Comment by mmotkim** [comment]
I just tried, it worked as well!

Also to answer your questions:

- Is`/sap/bc/ui5_ui5/sap/zatpr` the path of your ALP i.e. the original app? Yes
- You intend to deploy `jspdf `as part of your ADP? However so that it will work after deployment
- Your original ALP doesn't refer to `jspdf `at all? No it doesn't. I needed to add custom exporting features to the original app and ALP doesn't support controller code nor 3rd party libraries and the only solution was to use ADP. 
I decided on `exceljs `and `jspdf`/`js-pdf` after implementing `ui5-tooling-modules` because this tooling extension is theonly  method for 3rd party libs that I found to be working for ADP.

**Comment by tobiasqueck** [comment]
> I just tried, it worked as well!

I am happy to hear that. I'd suggest to use it as a workaround until #1049 is available. Afterwards, you shouldn't need it anymore.

**Comment by mmotkim** [comment]
@tobiasqueck  @petermuessig  
I just noticed today, both of your methods made the Preview Application work but used the entire codebase from a previous app version deployed to the backend.. haha

I was changing some code but didn't see anything different when reloading, even with new `console.log`.
A few days ago I did deploy for the first time to the server for testing, I had the `dist` folder saved and compared its `ExportToExcel.js` with the output when running the app to make sure.

**Comment by petermuessig** [comment]
But how could that be? In my suggested approach, the mapping is only redirecting the application variant local `resources` path. The application variant must still be loaded locally - or - hmm, no - the path the application variant is loaded is from `/sap/bc/ui5_ui5/sap/zatpr/~3652DD8F6F55485147ACA7924D0C9999~5` which is a backend URL and proxied to the ABAP system. Maybe this is the overall issue - why isn't this pointing to the local server? Or is there something missing? @tobiasqueck how is this supposed to work with the application variants? Should the URL point to the server root of localhost or to the proxied URL and the proxy redirects to the local application version? 

Maybe a solution is to redirect the full application? With Tobias suggestion slightly changed:

```yaml
- name: fiori-tools-preview
      afterMiddleware: fiori-tools-appreload
      configuration:
        flp:
          apps:
          - target: /
            componentId: customer.atpreportvariant
```

=> Redirecting the variant to the server root
