### ISSUE TITLE
Upgrading to `@ui5/cli` v4 breaks `sinon` import (maybe feat. `ui5-tooling-modules`)

### ISSUE THREAD

**Issue by HymanZHAN** [ui5-community/ui5-ecosystem-showcase#1196]
**Describe the bug**

After upgrading to ui5/cli@4, importing `sinon` is broken.

- We are using a newer version of `sinon` in our unit tests
- We import `sinon` in our tests via `import sinon from "sinon";`, the ES Module way
- And error is thrown on load: `require is not defined`

**To Reproduce**

1. Install `sinon` by `npm i -D sinon`
2. Install `ui5-tooling-modules` and `ui5-tooling-transpile`
3. Set up `unitTests.qunit.html`
  
  ```html
  <script src="/resources/qunit.js"></script>
  <script src="/resources/sinon.js"></script>
  <script>
      sap.ui.loader.config({
          map: {
              "*": {
                  qunit: null,
                  sinon: null,
              },
          },
      });
  </script>

  <script src="unitTests.qunit.js"></script>
   ```
4. Set up `unitTests.qunit.ts`

```ts
import sinon from "sinon";

QUnit.config.autostart = false;
```

The `sinon.js` JavaScript file is correctly loaded by ui5loader, but an error is raised on execution:

```
Uncaught ModuleError: Failed to resolve dependencies of '~anonymous~1.js'
 -> 'sinon.js': Failed to execute 'sinon.js': require is not defined
    at makeModuleError (http://localhost:3001/resources/ui5loader.js:1190:17)
    at Module.failWith (http://localhost:3001/resources/ui5loader.js:958:16)
    at http://localhost:3001/resources/ui5loader.js:2048:34
    at requireAll (http://localhost:3001/resources/ui5loader.js:1926:5)
    at executeModuleDefinition (http://localhost:3001/resources/ui5loader.js:2047:3)
    at Object.ui5Define [as define] (http://localhost:3001/resources/ui5loader.js:2123:3)
    at http://localhost:3001/test/unit/unitTests.qunit.js:4:8
Caused by: ModuleError: Failed to execute 'sinon.js': require is not defined
    at makeModuleError (http://localhost:3001/resources/ui5loader.js:1190:17)
    at Module.failWith (http://localhost:3001/resources/ui5loader.js:958:16)
    at execModule (http://localhost:3001/resources/ui5loader.js:1845:14)
    at requireModule (http://localhost:3001/resources/ui5loader.js:1718:5)
    at requireAll (http://localhost:3001/resources/ui5loader.js:1913:20)
    at executeModuleDefinition (http://localhost:3001/resources/ui5loader.js:2047:3)
    at Object.ui5Define [as define] (http://localhost:3001/resources/ui5loader.js:2123:3)
    at http://localhost:3001/test/unit/unitTests.qunit.js:4:8
Caused by: ReferenceError: require is not defined
    at eval (http://localhost:3001/resources/sinon.js?eval:3:19)
    at eval (<anonymous>)
    at execModule (http://localhost:3001/resources/ui5loader.js:1823:15)
    at requireModule (http://localhost:3001/resources/ui5loader.js:1718:5)
    at requireAll (http://localhost:3001/resources/ui5loader.js:1913:20)
    at executeModuleDefinition (http://localhost:3001/resources/ui5loader.js:2047:3)
    at Object.ui5Define [as define] (http://localhost:3001/resources/ui5loader.js:2123:3)
    at http://localhost:3001/test/unit/unitTests.qunit.js:4:8Caused by: ModuleError: Failed to execute 'sinon.js': require is not defined
    at makeModuleError (http://localhost:3001/resources/ui5loader.js:1190:17)
    at Module.failWith (http://localhost:3001/resources/ui5loader.js:958:16)
    at execModule (http://localhost:3001/resources/ui5loader.js:1845:14)
    at requireModule (http://localhost:3001/resources/ui5loader.js:1718:5)
    at requireAll (http://localhost:3001/resources/ui5loader.js:1913:20)
    at executeModuleDefinition (http://localhost:3001/resources/ui5loader.js:2047:3)
    at Object.ui5Define [as define] (http://localhost:3001/resources/ui5loader.js:2123:3)
    at http://localhost:3001/test/unit/unitTests.qunit.js:4:8
Caused by: ReferenceError: require is not defined
    at eval (http://localhost:3001/resources/sinon.js?eval:3:19)
    at eval (<anonymous>)
    at execModule (http://localhost:3001/resources/ui5loader.js:1823:15)
    at requireModule (http://localhost:3001/resources/ui5loader.js:1718:5)
    at requireAll (http://localhost:3001/resources/ui5loader.js:1913:20)
    at executeModuleDefinition (http://localhost:3001/resources/ui5loader.js:2047:3)
    at Object.ui5Define [as define] (http://localhost:3001/resources/ui5loader.js:2123:3)
    at http://localhost:3001/test/unit/unitTests.qunit.js:4:8Caused by: ReferenceError: require is not defined
    at eval (sinon.js?eval:3:19)
    at eval (<anonymous>)
    at execModule (ui5loader.js:1823:15)
    at requireModule (ui5loader.js:1718:5)
    at requireAll (ui5loader.js:1913:20)
    at executeModuleDefinition (ui5loader.js:2047:3)
    at Object.ui5Define [as define] (ui5loader.js:2123:3)
    at unitTests.qunit.ts:4:32
```

My `ui5-ut.yaml`:

```yaml
specVersion: "3.0"
metadata:
  name: com.sap.calm.imp.tkm.ui
customConfiguration:
  config-ui5-tooling-modules: &cfgModules
    debug: false
    minify: true
    addToNamespace: true
    babelConfig:
      sourceMaps: true
      ignore:
        - "**/*.d.ts"
      presets:
        - - "@babel/preset-env"
          - targets: defaults
        - "@babel/preset-typescript"
      plugins:
        - istanbul
type: application
framework:
  name: SAPUI5
  version: "1.130.8"
  libraries:
    - name: sap.f
    - name: sap.gantt
    - name: sap.m
    - name: sap.tnt
    - name: sap.ui.core
    - name: sap.ui.rta
    - name: sap.ushell
    - name: sap.uxap
resources:
  configuration:
    paths:
      webapp: webapp
server:
  settings:
    httpPort: 3001
    httpsPort: 3001
  customMiddleware:
    - name: ui5-tooling-transpile-middleware
      afterMiddleware: compression
    - name: ui5-tooling-modules-middleware
      afterMiddleware: ui5-tooling-transpile-middleware
      configuration:
        <<: *cfgModules
    - name: "@ui5/middleware-code-coverage"
      afterMiddleware: ui5-tooling-modules-middleware
      configuration:
        instrument:
          produceSourceMap: true
          coverageGlobalScope: "window.top"
          coverageGlobalScopeFunc: false
        excludePatterns:
          - "resources/"
          - "test/"
          - "localService/"
          - "DataHandler.js"
          - "typedef/"

```

**Expected behavior**
 
Importing the `sinon` installed by npm in my local `node_modules` folder should work.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chrome
 - Version: 134

**Additional context**

This setup has been working fine with `@ui5/cli` v3.

**Comment by petermuessig** [comment]
Hi @HymanZHAN 

IMO, the issue is not related to the `@ui5/cli` version. This may only be a coincidence. By default, when using the `ui5-tooling-modules` tooling extension it is converting those modules into UI5 AMD like modules - means using `sap.ui.define`. Those modules cannot be loaded via a script tag. Instead of loading `sinon` via `SCRIPT` tag, wouldn't it be sufficient to `import` it in the `unitTests.qunit.ts`? You may also need to use it in the TS code (maybe just by calling `console.log(sinon);`) since otherwise the `import` is removed by the TypeScript build. 

Maybe you can try this?

BR

**Comment by HymanZHAN** [comment]
Hi @petermuessig,

Thank for the reply. Removing the script tag import doesn't help though. The problem is that the content of `sinon.js` found by `ui5-tooling-modules` is not the same.

Under `@ui5/cli` v4:

```js
"use strict";

const createApi = require("./create-sinon-api");

module.exports = createApi();
```

Under `@ui5/cli` v3:

```js
sap.ui.define(["exports", "com/sap/calm/imp/tkm/ui/resources/node.process"], (function(l, n) {
    "use strict";
    /* Sinon.JS 19.0.2, 2024-09-13, @license BSD-3 */
    let u;
    !function l(n, u, e) {
        function t(o, i) {
            if (!u[o]) {
                if (!n[o]) {
                    var s = "function" == typeof require && require;
                    if (!i && s)
                        return s(o, !0);
                    if (r)
                        return r(o, !0);
                    var a = new Error("Cannot find module '" + o + "'");
                    throw a.code = "MODULE_NOT_FOUND",
                    a
                }
                var c = u[o] = {
                    exports: {}
                };
                n[o][0].call(c.exports, (function(l) {
                    return t(n[o][1][l] || l)
                }
                ), c, c.exports, l, n, u, e)
            }
            return u[o].exports
        }
        for (var r = "function" == typeof require && require, o = 0; o < e.length; o++)
            t(e[o]);
        return t
    }({
        1: [function(l, n, u) {
            const e = l("./sinon/behavior")
              , t = l("./sinon/create-sandbox")
              , r = l("./sinon/util/core/extend")
              , o = l("./sinon/util/fake-timers")
              , i = l("./sinon/sandbox")
              , s = l("./sinon/stub")
              , a = l("./sinon/promise")
              , c = l("nise")
              , f = l("assert");
            n.exports = function(n={
                sinonXhrLib: c
            }) {
                f(n?.sinonXhrLib, "No XHR lib passed in");
                const {sinonXhrLib: u} = n
                  , p = {
                    createSandbox: t,
                    match: l("@sinonjs/samsam").createMatcher,
                    restoreObject: l("./sinon/restore-object"),
                    expectation: l("./sinon/mock-expectation"),
                    timers: o.timers,
                    xhr: u.fakeXhr.xhr,
                    FakeXMLHttpRequest: u.fakeXhr.FakeXMLHttpRequest,
                    fakeServer: u.fakeServer,
                    fakeServerWithClock: u.fakeServerWithClock,
                    createFakeServer: u.fakeServer.create.bind(u.fakeServer),
                    createFakeServerWithClock: u.fakeServerWithClock.create.bind(u.fakeServerWithClock),
                    addBehavior: function(l, n) {
                        e.addBehavior(s, l, n)
                    },
                    promise: a
                }
                  , h = new i;
                return r(h, p)
            }
        }

// And the remaining hundreds of lines, omitted for brevity
```

The only code change in my commit is the `package.json` containing the upgrade to `@ui5/cli` v4, so I am pretty sure that's what messed up the resource resolving/transformation process. 

![Image](https://github.com/user-attachments/assets/949221b4-3af4-44d1-b8c3-13ca245f062b)

Maybe this gives you a better idea of what might have gone wrong.

**Comment by petermuessig** [comment]
I found your project and checked the setup. 

In the log during the build there was the following warning:

```
warn builder:custom-task:ui5-tooling-modules-task Skipping dependency "sinon" as it is not part of the dependencies in package.json!
```

This means that `sinon` isn't listed as a dependency in the package.json and thus ignored by the ui5-tooling-modules. 

By adding the `sinon` to the dependencies or using the configuration option `additionalDependencies` in the ui5-ut.yaml it also works with UI5 3.0:

```yaml
customConfiguration:
  config-ui5-tooling-modules: &cfgModules
    debug: false
    minify: true
    addToNamespace: true
    additionalDependencies:
      - "sinon"
```
