### ISSUE TITLE
[fiori-tools-servestatic] custom lib / path is not served in combination with CAP

### ISSUE THREAD

**Issue by T1mey** [ui5-community/ui5-ecosystem-showcase#1227]
Hello all,
 
we are facing some issues since a few days with loading a custom lib. It seems that a 
 
cds watch 
 
isn't serving paths of a Fiori elements app correctly which are configured over the middleware task fiori-tools-servestatic. The log says that it is served but over the browser we are not able to access it.
Over a ui serve of the app it's working.
 
```
server:
  customMiddleware:   
    - name: fiori-tools-servestatic
      afterMiddleware: compression
      configuration:
        paths:
          - path: /testIT
            src: "/home/user/projects/myproject/test"
```
 
As a result custom libs can not be loaded in BAS / Build Code when running cds watch.
 
CAP version is 9, but it is not working with the latest 8 version neither. 
"cds-plugin-ui5": "^0.13.0" ist in use as well.
 
Anybody an idea what has changed?
