### ISSUE TITLE
multiple ui5-middleware-simpleproxy

### ISSUE THREAD

**Issue by Szbuli** [ui5-community/ui5-ecosystem-showcase#397]
I would like to simulate scp neo destinations for local development.
We have two destinations in the cloud, which means i have to have two ui5-middleware-simpleproxy. 

```
  - name: ui5-middleware-simpleproxy
    afterMiddleware: compression
    mountPath: /uri1
    configuration:
      baseUri: "uri1"
      username: user1
      password: pw1
  - name: ui5-middleware-simpleproxy
    afterMiddleware: compression
    mountPath: /uri2
    configuration:
      baseUri: "uri2"
      username: user2
      password: pw2
```

If i set the username+password in the yaml, everything works fine. But i would rather not, as ui5.yaml is not ignored in git.

I would like to set the username + password as an env variable, but the problem is the two ui5-middleware-simpleproxy share the same parameter.

Could you help me how can i solve this problem?
