### ISSUE TITLE
ui5-middleware-cfdestination - auth configuration bug

### ISSUE THREAD

**Issue by iggycoder** [ui5-community/ui5-ecosystem-showcase#503]
There seems to be a bug introduced in PR #492. The newly introduced `ui5.yaml` configuration `authenticationMethod` is not being evaluated in the routes as far as I can tell. As I understand, this configuration should overwrite the `xs-app.json` configuration of the app router. Right now my setup is not working.

Let me explain:

I did setup route authentication in my app router's `xs-app.json`. This `xs-app.json` is being referenced (and reused) inside the customMiddleware of the SAP-UI5 project. Running locally, I wish to **not** use any route authentication and instead configured the newly `authenticationMethod` property to `"none"`.

@d-sooter

Thanks for any input/help.

**Comment by vobu** [comment]
Without having validated the bug, you bring up the proverbial thorn in my side - there are no tests for this and all other `ui5-middleware-*` and `ui5-task-*`. That's why we serve ourselves these kind of regressions, grmpf, mea culpa, mea maxima culpa. I'll take this as a 🥾 to finally introduce a testing mechanism.

@d-sooter could you please take a look meanwhile and help out @iggycoder?

**Comment by iot-cpars** [comment]
@iggycoder can you provide a sample of you config? We are using it locally as well without any probems. The default is none as well so you shouldnt need to pass anything if you dont want auth. 

Kind regards

**Comment by petermuessig** [comment]
Just published version 0.4.1 right now: 
https://www.npmjs.com/package/ui5-middleware-cfdestination

Please verify whether this fixes the issue.

**Comment by iggycoder** [comment]
@iot-cpars Please let us know if my changes affect your setup in any way.
@petermuessig Thanks for the fast release.

**Comment by iggycoder** [comment]
just as a reference - my config which only works since my bugfix:
`xs-app.json`
```json
{
  "welcomeFile": "/sapcpui/",
  "authenticationMethod": "route",
  "websockets": {
    "enabled": true
  },
  "logout": {
    "logoutEndpoint": "/do/logout"
  },
  "routes": [
    {
      "source": "^/srv/(.*)$",
      "target": "$1",
      "authenticationType": "xsuaa",
      "destination": "service-api",
      "csrfProtection": true,
      "scope": [
        "uaa.user"
      ]
    }
  ]
}
```
`ui5.yaml`
```yaml
server:
  customMiddleware:
    - name: ui5-middleware-cfdestination
      afterMiddleware: compression
      configuration:
        authenticationMethod: none
        debug: true
        port: 1091
        xsappJson: ../router/xs-app.json
        destinations:
          - name: service-api
            url: http://localhost:8080
            # for debugging purposes, set connection timeout to 15 minutes
            timeout: 900000
```
