### ISSUE TITLE
middleware-livereload not reloading Chrome

### ISSUE THREAD

**Issue by C3ntraX** [ui5-community/ui5-ecosystem-showcase#533]
Hello together,

I have the problem, that the middleware-livereload is not reloading the browser.
The middleware recognizes the changes but it doesn´t know about the open browser.

The script I use with yarn:
"start": "ui5 serve --open index.html",

Console output inlusive change:
![image](https://user-images.githubusercontent.com/44802503/128320378-6014551e-8977-4c74-ba8d-258210342108.png)

The config: 

![image](https://user-images.githubusercontent.com/44802503/128320223-c2a58ef4-8fd5-40ff-a373-1eaee7bc5818.png)

I executed your example and the console printed the line
[Browsersync] Browser Connected: Chrome, version: 92.0.4515.131

but not in my case... could this be the issue? I mean, I don´t know, where the debug come from. 

I would appreciate any help. Thanks!

**Comment by vobu** [comment]
the `console` output looks fine - both `server`/app on port 3000 and `livereload` on port 35730 are started correctly.
i just tried to reproduce this (via `yo easy-ui5`, node 16.2.0) and things work as expected:

`ui5.yaml`:
```yaml
specVersion: "2.2"
metadata:
  name: myUI5App_uimodule
type: application
resources:
  configuration:
    paths:
      webapp: uimodule/webapp
framework:
  name: OpenUI5
  version: 1.84.0
  libraries:
    - name: sap.ui.core
    - name: sap.m
    - name: sap.ui.layout
    - name: themelib_sap_fiori_3
server:
  settings:
    httpPort: 3000
  customMiddleware:
    - name: ui5-middleware-livereload
      afterMiddleware: compression
      configuration:
        port: 35730
        debug: true
        path: uimodule/webapp
```

`package.json`:
```json
{
  "name": "myUI5App",
  "version": "0.0.1",
  "scripts": {
    "start": "ui5 serve --config=uimodule/ui5.yaml  --open index.html",
    "build:ui": "run-s  build:uimodule",
    "test": "run-s lint karma",
    "karma-ci": "karma start karma-ci.conf.js",
    "clearCoverage": "shx rm -rf coverage",
    "karma": "run-s clearCoverage karma-ci",
    "lint": "eslint .",
    "serve:uimodule": "ui5 serve --config=uimodule/ui5.yaml",
    "build:uimodule": "ui5 build --config=uimodule/ui5.yaml --clean-dest --dest uimodule/dist --include-task=generateManifestBundle"
  },
  "devDependencies": {
    "shx": "^0.3.3",
    "@ui5/cli": "^2.12.0",
    "ui5-middleware-livereload": "^0.5.4",
    "karma": "^6.3.4",
    "karma-chrome-launcher": "^3.1.0",
    "karma-coverage": "^2.0.3",
    "karma-ui5": "^2.3.4",
    "npm-run-all": "^4.1.5",
    "eslint": "^7.32.0"
  },
  "ui5": {
    "dependencies": [
      "ui5-middleware-livereload"
    ]
  }
}
```

Output:
```shell
~/_tmp/test-livereload> npm start                                                    

> myUI5App@0.0.1 start
> ui5 serve --config=uimodule/ui5.yaml  --open index.html

info normalizer:translators:ui5Framework Using OpenUI5 version: 1.84.0
LiveReload is waiting for a browser to connect...

Protocol version: 7
Exclusions: /\.git\//,/\.svn\//,/\.hg\//
Extensions: xml,json,properties,html,css,js,png,gif,jpg,php,php5,py,rb,erb,coffee
Polling: false


info server:custommiddleware:livereload Livereload connecting to port 35730 for path uimodule/webapp
Watching /Users/vbuzek/_tmp/test-livereload/uimodule/webapp...

info server:custommiddleware:livereload Livereload server started!
Server started
URL: http://localhost:3000
Browser connected.

Client message: {"command":"hello","protocols":["http://livereload.com/protocols/official-6","http://livereload.com/protocols/official-7"],"ver":"3.3.2","snipver":1}

Client requested handshake...

Handshaking with client using protocol 7...

Client message: {"command":"info","plugins":{"less":{"disable":false,"version":"1.0"}},"url":"http://localhost:3000/index.html"}

Server received client data. Not sending response.

Saw change to /Users/vbuzek/_tmp/test-livereload/uimodule/webapp/view/MainView.view.xml

Reloading: /Users/vbuzek/_tmp/test-livereload/uimodule/webapp/view/MainView.view.xml
```

What `node` version are you using?
Maybe try upgrading your npm deps in `package.json` and see if that resolves the issue?
