### ISSUE TITLE
[ui5-middleware-cfdestination] Replacement of xsappPath hardcoded

### ISSUE THREAD

**Issue by Magoli1** [ui5-community/ui5-ecosystem-showcase#547]
**Describe the bug**
When configuring a path to the `xs-app.json` file, where the file is named other than `xs-app.json`, eg. `xs-app-local.json`, the approuter can not find the `default-env.json` anymore, as the passed xsappPath is wrong.

This error originates from this [hardcoded replacement](https://github.com/ui5-community/ui5-ecosystem-showcase/blob/9288a744104a2d31db532c777a356195a3f4ef15/packages/ui5-middleware-cfdestination/lib/cfdestination.js#L44).

Example config:
````yaml
  - name: ui5-middleware-cfdestination
    afterMiddleware: compression
    configuration:
      authenticationMethod: "route"
      allowServices: true
      debug: true
      port: 5000
      xsappJson: "xs-app-local.json"
````

What do you think, should we just cut of the last part of the path everything after the last slash like so `./dev/xs-app-local.json` -> `./dev/` ? Just thinking if that would cover all situations.

Cheers
Robert 🚀
