### ISSUE TITLE
ui5-tooling-modules: not able to use @supabase/supabase-js package

### ISSUE THREAD

**Issue by ekansh005** [ui5-community/ui5-ecosystem-showcase#564]
**Describe the bug**
Hi, I am not able to use '@supabase/supabase-js' package (https://github.com/supabase/supabase-js) in the my controller.js file. It fails to load '@supabase/supabase-js.js' instead of the main file of this package which resolves to dist/main/index.js. I created a simple js file and used  `require.resolve("@supabase/supabase-js")`  to test it and it resolves correctly to installed node_modules/...../main/index.js file.

@petermuessig 

**To Reproduce**
1. Create a simple freestyle UI5 app
2. Setup ui5-tooling-modules
3. Run `npm install @supabase/supabase-js`
4. Include "@supabase/supabase-js" in controller dependencies. 
5. `npm start` and check error in browser console

**Expected behavior**
I expect ui5-tooling-modules to load correct dependency which is 'index.js' file coming from request.resolve() instead of looking for supabase-js.js file

**Screenshots**
![image](https://user-images.githubusercontent.com/439184/152646022-a33f79ff-1420-4e0c-9a41-12df3abe7dc3.png)

**Comment by petermuessig** [comment]
Hi @ekansh005 ,

I can confirm that there is an issue when using the current rollup bundling with `@supabase/supabase-js`. 

In my case it is even worse that after configuring the `ui5-tooling-modules` and `@supabase/supabase-js` in the `package.json`:

```json
{
  "name": "myapp",
  [...]
  "devDependencies": {
    [...]
    "ui5-middleware-livereload": "^0.5.8",
    "ui5-tooling-modules": "^0.1.1"
  },
  "ui5": {
    "dependencies": [
      "ui5-middleware-livereload",
      "ui5-tooling-modules",
      "@supabase/supabase-js"
    ]
  },
  "dependencies": {
    "@supabase/supabase-js": "^1.30.0"
  }
}
```

*Attention: you also need to add the dependency to supabase in the ui5 > dependencies section!*

The server now stops working:

```sh
Server received client data. Not sending response.

XXX /Users/XXX/SAPDevelop/temp/com.myorg.myapp/node_modules/@supabase/supabase-js/dist/main/index.js
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
[!] Error: unfinished hook action(s) on exit:
(commonjs) load "\u0000/Users/d039071/SAPDevelop/temp/com.myorg.myapp/node_modules/websocket/package.json?commonjs-proxy"
(node-resolve) resolveId "/Users/d039071/SAPDevelop/temp/com.myorg.myapp/node_modules/websocket/lib/version.js" "\u0000/Users/d039071/SAPDevelop/temp/com.myorg.myapp/node_modules/websocket/lib/version.js?commonjs-proxy"

ERROR: "start:ui5" exited with 1.
```

The issue is related to the `websocket` dependency, which is requiring its `package.json` in `lib/version.js`:

```js
module.exports = require('../package.json').version;
```

I would say, we need to add the JSON bundling to the plugin as well so that it is able to handle this kind of imports/requires as well. 

I will give it a try a bit later and can then hopefully provide a fix asap.

**Comment by petermuessig** [comment]
ui5-tooling-modules 0.1.2 has been released just right now.

**Comment by ekansh005** [comment]
Hi @petermuessig 
Thanks for your quick support but I am still facing the same problem. I updated the package to 0.1.2 and added supabase package to ui5.dependencies. Here is my package.json.
```
{
  "name": "test",
  "version": "0.0.1",
  "private": true,
  "sapuxLayer": "CUSTOMER_BASE",
  "description": "A Fiori application.",
  "keywords": [
    "ui5",
    "openui5",
    "sapui5"
  ],
  "main": "webapp/index.html",
  "scripts": {
    "start": "fiori run --open 'index.html'",
    "start-local": "fiori run --config ./ui5-local.yaml --open 'test/flpSandbox.html'",
    "start-noflp": "fiori run --open 'index.html'",
    "build": "ui5 build -a --clean-dest --include-task=generateManifestBundle generateCachebusterInfo",
    "deploy": "fiori verify",
    "deploy-config": "fiori add deploy-config",
    "unit-tests": "fiori run --open test/unit/unitTests.qunit.html",
    "int-tests": "fiori run --open test/integration/opaTests.qunit.html"
  },
  "devDependencies": {
    "@sap/ux-ui5-tooling": "^1.4.7",
    "@ui5/cli": "^2.14.4",
    "@ui5/fs": "^2.0.6",
    "@ui5/logger": "^2.0.1",
    "rimraf": "3.0.2",
    "ui5-tooling-modules": "^0.1.2"
  },
  "dependencies": {
    "@supabase/supabase-js": "^1.30.0"
  },
  "ui5": {
    "dependencies": [
      "@sap/ux-ui5-tooling",
      "ui5-tooling-modules",
      "@supabase/supabase-js"
    ]
  }
}
```
And this is my controller
```
sap.ui.define(
  ["sap/ui/core/mvc/Controller", "@supabase/supabase-js"],
  /**
   * @param {typeof sap.ui.core.mvc.Controller} Controller
   */
  function (Controller, sb) {
    "use strict";

    return Controller.extend("com.ekansh.test.controller.View1", {
      onInit: function () {
        console.log(sb);
      },
    });
  }
);
```
What am I doing wrong?

**Comment by petermuessig** [comment]
Hmm, that's strange -  I tested exactly this scenario and it worked for me. Did you run `npm install` or `yarn` after changing the version? Please make sure to delete the `package-lock.json` or `yarn-lock.json` and the `node_modules` to ensure that the latest version of the middleware is used. You can also check in `node_modules/ui5-tooling-modules/package.json` is also having the version `0.1.2`.

**Comment by petermuessig** [comment]
BTW: the NPM packages used by the `ui5-tooling-modules` don't need to be added to `ui5` > `dependencies`.  The resolution of the NPM packages is not happening via the UI5 tooling virtual file system so the standard dependency is sufficient.

**Comment by ekansh005** [comment]
Yes, in fact I did `npm update` so the packages were updated automatically. Anyhow, I deleted the `package-lock.json` and `node_modules` and did a fresh `npm install`. I can confirm that the version is 0.1.2. 
FYI, the project was generated from Fiori tools application generator in vscode and not with `easy-ui5`. I don't think that it makes any difference but just thought of mentioning.
I am following the setup instructions provided at https://www.npmjs.com/package/ui5-tooling-modules . The usage section in this documentation has the `ui5-tooling-modules` mentioned in the `ui5` > `dependencies`. If I remove it and run `npm start`, it fails with error:
`middlewareRepository: Unknown Middleware ui5-tooling-modules-middleware`
Here is my `ui5.yaml` file:
```
specVersion: "2.4"
metadata:
  name: "test"
type: application
builder:
  customTasks:
    - name: ui5-tooling-modules-task
      afterTask: replaceVersion
server:
  customMiddleware:
    - name: ui5-tooling-modules-middleware
      afterMiddleware: compression
    - name: fiori-tools-proxy
      afterMiddleware: compression
      configuration:
        ignoreCertError: false # If set to true, certificate errors will be ignored. E.g. self-signed certificates will be accepted
        backend:
          - path: /sap
            url: https://xxxx.yyyy.fi:44300/
        ui5:
          path:
            - /resources
            - /test-resources
          url: https://ui5.sap.com
          version: # The UI5 version, for instance, 1.78.1. Empty means latest version
    - name: fiori-tools-appreload
      afterMiddleware: compression
      configuration:
        port: 35729
        path: webapp

```
My project is very basic so I can even send you the git repo link if you wish.

**Comment by petermuessig** [comment]
Yes, @ekansh005, please send me your repo. 

BTW: i didn't mean to remove the tooling from UI5 > dependencies ; just the @supabase entry. This is sufficient as normal dependency.

**Comment by petermuessig** [comment]
Thanks for the example @ekansh005 - I can confirm that the issue if related to the Fiori Tools Proxy which intercepts the requests and the ui5-tooling-modules-middleware is not used to handle the request:

![image](https://user-images.githubusercontent.com/1589419/153155388-5e38cbfc-f3f0-45e2-a71c-12c3a5ff9bf0.png)

I'll check whether there are some possibilities to fix this

**Comment by petermuessig** [comment]
Hi @ekansh005 ,

the trick is the following:

```
server:
  customMiddleware:
    - name: ui5-tooling-modules-middleware
      afterMiddleware: compression
    - name: fiori-tools-proxy
      afterMiddleware: ui5-tooling-modules-middleware
      configuration:
```

You need to ensure that the fiori-tools-proxy is running after the ui5-tooling-modules-middleware by explicitly set the:

`afterMiddleware: ui5-tooling-modules-middleware`

This should solve your issue.
