### ISSUE TITLE
[ui5-tooling-transpile-task] General question about sources

### ISSUE THREAD

**Issue by AdrianDengusiak** [ui5-community/ui5-ecosystem-showcase#742]
Hi,

I started to use **ui5-tooling-transpile** to transpile my code from ES6+ to ES5, and it works very well when I preview my app locally, so both original files + transpiled files are available while debugging. As documentation says, because of the sourcemap, setting breakpoints in the original source will cause the debugger to stop when the corresponding transpiled source code is reached. And it's working fine, so I can debug my original code.

The problem is while deploying application to BTP Work Zone standard edition. It might be I misunderstood something too.
This is my **ui5-deploy.yaml**, that is used while building **MTA** of the project.

```yaml
# yaml-language-server: $schema=https://sap.github.io/ui5-tooling/schema/ui5.yaml.json
specVersion: '2.4'
metadata:
  name: com.test.app
type: application
resources:
  configuration:
    propertiesFileSourceEncoding: UTF-8
builder:
  resources:
    excludes:
      - "/test/**"
      - "/localService/**"
  customTasks:
  - name: ui5-tooling-transpile-task
    afterTask: replaceVersion
    configuration:
      debug: true
      transformAsyncToPromise: true
      removeConsoleStatements: true
  - name: webide-extension-task-updateManifestJson
    afterTask: ui5-tooling-transpile-task
    configuration:
      appFolder: webapp
      destDir: dist
  - name: ui5-task-zipper
    afterTask: generateCachebusterInfo
    configuration:
      archiveName: comtestapp
      additionalFiles:
      - xs-app.json

```

I use **ui5-tooling-transpile-task** to trigger transpiling process during build.

The result in **dist** folder is that I can't see my original sources, e.g. containing async functions.
Main.controller-dbg.js contains transpiled code (async converted to Promise, etc.)
Main.controller..js contains transpiled code + is minified too.
There's Main.js.map too, responsible for sourcemap.

When I run my deployed app in FLP, I would like to debug my original sources - the same way as previewing it locally (ui5-tooling-transpile-middleware works as expected). Unfortunately, they're not part of deployed bundle. I tried to find some settings, but haven't found anything.

Currently, I can see my dbg sources in DevTools, but they're transpiled.

My question:
- Is it possible to keep original sources in dist and use while debugging the app after deployment? Can it work like middleware while previewing app locally?
