### ISSUE TITLE
[ui5-middleware-simpleproxy] How could i use this package behind a company proxy server

### ISSUE THREAD

**Issue by zouyi100** [ui5-community/ui5-ecosystem-showcase#748]
Hi Team,
Now i'm working in a network hehind a proxy server. Now i want to send the req to Northwind OData serve, config like below:
```
server:
  customMiddleware:
  - name: ui5-middleware-simpleproxy
    mountPath: /Northwind/v2/northwind/northwind.svc/
    afterMiddleware: compression
    configuration:
      baseUri: "https://services.odata.org/v2/northwind/northwind.svc"
      path: webapp
```
Now it still showing like https://services.odata.org/v2/northwind/northwind.svc 404 NOT FOUND.
Because it's like proxy the /northind to the real https:// url. But the real url is not found without the company proxy.

So is it posible for adding some config in this middleware to add a proxy before sending the req to real url.

Thank you :)
