### ISSUE TITLE
[ui5-middleware-cfdestination/ui5-tooling-transpile] Typescript transpilation doesn't work with cfdestination middleware

### ISSUE THREAD

**Issue by aspirio187** [ui5-community/ui5-ecosystem-showcase#814]
**Describe the bug**

When using `ui5-tooling-transpile` in combination with `ui5-middleware-cfdestination`, TypeScript files are not transpiled when running `ui5 serve` command

The app works as expected when loading the built folder

@petermuessig I saw that you commented a similar issue [here](https://github.com/ui5-community/ui5-ecosystem-showcase/issues/665#issuecomment-1369663582).

Here are the logs returned by the app:

```plaintext
#2.0#2023 08 28 15:14:19:345#+02:00#ERROR#/Handler#####d2c24a2c-fa13-4d13-a573-8de5d9b5b556####kbI_La1Uaoki8eQm4TJVJugQtcp0W4z-######lluwi8uo#PLAIN##GET request to /Component.js completed with status 404 ENOENT: no such file or directory, stat '/home/soultan/SAP-samples/ui5.typescript.sample/webapp/Component.js'#
#2.0#2023 08 28 15:14:19:351#+02:00#ERROR#/Handler#####065e16dc-27fc-44b3-a094-18171f98059a####3eXNmW43EPgW-HDPYwSjqvQBEOgJHLqk######lluwi8ut#PLAIN##GET request to /Component.js completed with status 404 ENOENT: no such file or directory, stat '/home/soultan/SAP-samples/ui5.typescript.sample/webapp/Component.js'#
```

**To Reproduce**

1. Generate a simple ui5 typescript app with yo (no service required to test this issue)
2. Create a xs-app.json file in the app folder with a similar configuration
```json
{
	"authenticationMethod": "route",
	"welcomeFile": "/webapp/index.html",
	"logout": {
		"logoutEndpoint": "/do/logout"
	},
	"routes": [
		{
			"source": "^/dbg/(.*)$",
			"target": "$1",
			"localDir": "webapp"
		}
	]
}

```
4. Add the latest version of __ui5-middleware-cfdestination__ in the package.json or run the following command in the app folder `npm i ui5-middleware-cfdestination`
5. Modify the ui5.yaml file and include the __ui5-middleware-cfdestination__ similar to this:
```yaml
specVersion: "3.0"
metadata:
  name: ui5.typescript.sample
type: application
framework:
  name: SAPUI5
  version: "1.116.0"
  libraries:
    - name: sap.m
    - name: sap.ui.core
    - name: themelib_sap_horizon
    - name: sap.ui.layout
builder:
  customTasks:
    - name: ui5-tooling-transpile-task
      afterTask: replaceVersion
    - name: ui5-tooling-modules-task
      afterTask: replaceVersion
      configuration:
        addToNamespace: true
server:
  customMiddleware:
    - name: ui5-tooling-transpile-middleware
      afterMiddleware: compression
    - name: ui5-middleware-livereload
      afterMiddleware: compression
    - name: ui5-tooling-modules-middleware
      afterMiddleware: compression
    - name: ui5-middleware-cfdestination
      afterMiddleware: compression
      configuration:
        debug: false
        allowServices: true
        allowLocalDir: true
        port: 5005
        xsappJson: xs-app.json
        destinations:
        - name: srv
          url: http://localhost:4004
          forwardAuthToken: true
```
6. Run the following command `ui5 serve -o /dbg/index.html` (If the yo generator created an **index-cdn.html** file, in the browser open the following url **http://localhost:5005/dbg/index-cdn.html** otherwise just open **http://localhost:5005/dbg/index.html**)

**Expected behavior**

The app should open and we should be able to debug the files.

**Screenshots**

**The way the app should work**

![image](https://github.com/ui5-community/ui5-ecosystem-showcase/assets/56565073/f6cc5173-30c2-4cda-bbaa-bff2a643e460)

![image](https://github.com/ui5-community/ui5-ecosystem-showcase/assets/56565073/a951ef9c-1af5-404b-95fb-e52b0b66e0bd)

**What we get instead**

![image](https://github.com/ui5-community/ui5-ecosystem-showcase/assets/56565073/6529b2a4-880d-4aea-ba5c-025954880707)

![image](https://github.com/ui5-community/ui5-ecosystem-showcase/assets/56565073/12a49221-2994-4448-9120-7d0a57e1180d)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser: Chrome
 - Version: 116.0.5845.111 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**

We are using the SAPUI5 version __1.116.0__

**Comment by petermuessig** [comment]
Hi @aspirio187 ,

I think this is an ordering issue of the middlewares - the last configured middleware comes first and therefore the `cfdestination` comes before the `transpile` middleware. Can you try this order here:

```yaml
server:
  customMiddleware:
    - name: ui5-tooling-transpile-middleware
      afterMiddleware: compression
    - name: ui5-tooling-modules-middleware
      afterMiddleware: ui5-tooling-transpile-middleware
    - name: ui5-middleware-cfdestination
      afterMiddleware: ui5-tooling-transpile-middleware
      configuration:
        debug: false
        allowServices: true
        allowLocalDir: true
        port: 5005
        xsappJson: xs-app.json
        destinations:
        - name: srv
          url: http://localhost:4004
          forwardAuthToken: true
    - name: ui5-middleware-livereload
      afterMiddleware: compression
```

I moved the `livereload` at the end to ensure that this one comes first and then I ordered this other middlewares using the `afterMiddleware` configuration to ensure that the order is the following: `livereload` > `transpile` > `modules` > `cfdestination`. 

Keep my fingers crossed that this works... 😉
