### ISSUE TITLE
App can't find external package after deployment

### ISSUE THREAD

**Issue by MillCreeker** [ui5-community/ui5-ecosystem-showcase#849]
I followed the instructions, and they work perfectly fine when running the app locally.
When deploying the app, tho, it says "failed to load 'tesseract.js.js' from /sap/bc/ui5_ui5/ui2/ushell/resources[...]".

 - Browser: Chrome
 - Chrome version: 115.0.5790.171
 - Fiori version: 1.71.47
 - UI5 version: 3.6.0
 - ui5-tooling-modules version: 3.0.8

## ui5.yaml
```yaml
specVersion: "3.0"
metadata:
  name: <com.my.org>
type: application
builder:
  customTasks:
    - name: ui5-tooling-modules-task
      afterTask: replaceVersion
server:
  customMiddleware:
    - name: ui5-tooling-modules-middleware
      afterMiddleware: compression
    - name: fiori-tools-proxy
      afterMiddleware: ui5-tooling-modules-middleware
      configuration:
        ignoreCertError: true
        ui5:
          path:
            - /resources
            - /test-resources
          url: https://ui5.sap.com
        backend:
          - path: /sap
            url: <url>
            client: '001'
    - name: fiori-tools-appreload
      afterMiddleware: compression
      configuration:
        port: <port>
        path: webapp
        delay: 300
    - name: fiori-tools-preview
      afterMiddleware: fiori-tools-appreload
      configuration:
        component: <com.my.org>
        ui5Theme: sap_fiori_3
```

## package.json
```json
{
    "name": "myApp",
    "version": "0.0.1",
    "private": true,
    "description": "A Fiori application.",
    "keywords": [
        "ui5",
        "openui5",
        "sapui5"
    ],
    "main": "webapp/index.html",
    "dependencies": {
        "cordova": "^6.1.1",
        "latest": "^0.2.0",
        "node": "^16.0.0",
        "node.js": "^0.0.1-security",
        "tesseract.js": "^4.1.2"
    },
    "devDependencies": {
        "@sap/ux-ui5-tooling": "^1.9.5",
        "@ui5/cli": "^3.6.0",
        "rimraf": "^3.0.2",
        "ui5-task-flatten-library": "0.2.5",
        "ui5-tooling-modules": "*"
    },
    "scripts": {
        [...]
    },
    "sapuxLayer": "CUSTOMER_BASE",
    "ui5": {
        "dependencies": [
            "ui5-task-flatten-library"
        ]
    }
}
```

## ui5-deploy.yaml
```yaml
# yaml-language-server: $schema=https://sap.github.io/ui5-tooling/schema/ui5.yaml.json

specVersion: "2.6"
metadata:
  name: <com.my.org>
type: application
resources:
  configuration:
    propertiesFileSourceEncoding: UTF-8
builder:
  resources:
    excludes:
      - /test/**
      - /localService/**
      - /node_modules/
  customTasks:
    - name: deploy-to-abap
      afterTask: generateCachebusterInfo
      configuration:
        ignoreCertError: true
        target:
          url: <url>
          client: "<client>"
          auth: basic
          credentials:
          username: env.DEPLOYMENT_USER
          password: env.DEPLOYMENT_PASSWORD
        app:
          name: <MY_APP>
          description: <My_app>
          package: <Z_PACKAGE>
          transport: <transport>
        exclude:
          - /test/
```

I hope it's not because the *ui5-deploy.yaml*'s *specVersion* is below *3.0*. When changing it, the deployment doesn't work. In this case, we'd have to change our live UI5 version (I think).

**Comment by petermuessig** [comment]
@MillCreeker 

did you try the `addToNamespace` option for the task?

```yaml
builder:
  customTasks:
    - name: ui5-tooling-modules-task
      afterTask: replaceVersion
      configuration:
        addToNamespace: true
```

This option copies the external package into the namespace of the application under `thirdparty` and rewrites all usages via `sap.ui.define`, `sap.ui.require`, and `sap.ui.require.toUrl` so that this external package becomes an exclusive one for your application inside the local namespace.

HTH
