### ISSUE TITLE
[ui5-middleware-cfdestination] middleware ignores configuration and starts approuter at port 8080

### ISSUE THREAD

**Issue by jump912** [ui5-community/ui5-ecosystem-showcase#910]
Following the example [here](https://www.npmjs.com/package/ui5-middleware-cfdestination#usage), we configured the cfdestination middleware to use the port 5000. However, when we start the app using command `fiori run --config ./ui5-local.yaml`, the following error is observed in the terminal:

![image](https://github.com/ui5-community/ui5-ecosystem-showcase/assets/1579308/81304687-bdaa-4a3e-96b6-e2c709fbc60e)

Below are the content of our ui5-local.yaml and xs-app2.json.

content in ui5-local.yaml. 
``` yaml
specVersion: "3.0"
metadata:
  name: com.test.reusecomponent
type: application
framework:
  name: SAPUI5
  version: 1.110.0
  libraries:
    - name: sap.m
    - name: sap.ui.core
    - name: sap.ushell
    - name: sap.f
    - name: sap.ui.comp
    - name: sap.ui.generic.app
    - name: sap.suite.ui.generic.template
    - name: themelib_sap_horizon
server:
  customMiddleware:
    - name: ui5-middleware-cfdestination
      afterMiddleware: compression
      configuration:
        authenticationMethod: "route" # "none" || "route", default: "none"
        allowServices: true # allows BTP services like SAP IoT to be used
        debug: true
        port: 5000
        xsappJson: "xs-app2.json"
        destinations:
          # check that the destination name (here: "backend") matches your router in xs-app.json
          - name: "riz-inno-sdm"
            url: "https://api-sdm-di.cfapps.us10.hana.ondemand.com"

```

content in xp-app2.json
``` json
{
    "welcomeFile": "/index.html",
    "authenticationMethod": "route",
    "logout": {
        "logoutEndpoint": "/logout",
        "logoutPage": "/logout-page.html"
    },
    "routes": [
        {
            "source": "^/api/(.*)$",
            "target": "$1",
            "destination": "riz-inno-sdm",
            "authenticationType": "xsuaa",
            "endpoint": "ecmservice"
        }
    ]
}
```
