### ISSUE TITLE
[ui5-tooling-modules] How to bundle third party npm modules in a library?

### ISSUE THREAD

**Issue by swayongshen** [ui5-community/ui5-ecosystem-showcase#990]
**Problem**: I have a UI5 Typescript library with some custom controls that depend on [fabricjs](https://www.npmjs.com/package/fabric). I have added `ui5-tooling-modules-task` as a `customTask` and `fabricjs` is indeed bundled as `dist/resources/fabric.js` when the library is built. 

However, in the application that consumes this library, when my control is loaded, this error is shown which suggests that the application is trying to load its own version of `fabric.js` instead of using the one from my library.

<img width="670" alt="image" src="https://github.com/ui5-community/ui5-ecosystem-showcase/assets/52824657/ed418b87-685a-48e0-a2b2-fa90f2e0c931">

**Comment by petermuessig** [comment]
Make sure that you use the `addToNamespace` option in the `ui5.yaml` for the `ui5-tooling-modules`:

**`ui5.yaml`**
```yaml
[...]
builder:
  customTasks:
    - name: ui5-tooling-modules-task
      afterTask: replaceVersion
      configuration:
        addToNamespace: true
```

It ensures to include the `fabric.js` in the namespace of your application. 

You can find more about this option here: https://www.npmjs.com/package/ui5-tooling-modules
