### ISSUE TITLE
[cds-plugin-ui5] - hybrid testin in sap bas 

### ISSUE THREAD

**Issue by T0bbes** [ui5-community/ui5-ecosystem-showcase#993]
Hi all,

I have a SAP CAP project with a few CAP services and a few custom UI5/Fiori apps. 
Deployed everything works fine. Now I wanted to try these UI5 apps "locally" in SAP BAS. 

After a few hours I have to give up and hope that you can help me. 
The project has the classic structure, so the services are in the `srv` directory and the WebApps are in the `app/App1/` directory. In my root packge.json I have added the plugin `cds-plugin-ui5` and I start my cds server with `cds watch --profile hybrid`. 

At the moment I have the following UI5.yaml configuration:
```
specVersion: "3.2"
metadata:
  name: XYZ
type: application
server:
  customMiddleware:
    - name: fiori-tools-servestatic
      afterMiddleware: compression
      configuration:
        paths:
        - path: /YYY
          src: "../../../lib..."
    - name: fiori-tools-proxy
      afterMiddleware: compression
      configuration:
        ignoreCertError: false 
        backend:
          - path: /odata/v2
            url: http://localhost:4004
          - path: /resources
            url: https://ui5.sap.com
          - path: /test-resources
            url: https://ui5.sap.com
          - path: /sap
            url: http://XYZ.de:443
            client: '010'
            destination: XYZ

```
All OData services, both my local cap services as well as the on-premise odata interfaces are successfully accessed. The metadata is loaded successfully and I can see data. 

The only problem is that the **Component-preload.js** could not be found. Everything could be loaded, expect this one file. 

I can change the UI5.yaml a little bit, then the file is found again, but then the OData interfaces could no longer be found. 
What am I missing? Can anyone of you help me? Unfortunately I can't find a complete cap example that shows hybrid testing with ui5 in SAP BAS :( At the moment I can only load one or the other.

Thank you very much!
